# Generated by Django 3.1.5 on 2021-01-15 20:53

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=10, region=None),
        ),
    ]
