# Generated by Django 3.1.5 on 2021-01-16 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_customer_job_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.IntegerField(choices=[(1, '    open'), (2, 'pending'), (3, 'closed')], default=1),
        ),
    ]
